# Generated by Django 4.1.7 on 2023-03-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField()),
                ('rate', models.PositiveSmallIntegerField(blank=True)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Ограничение кол-ва определенного товара на складе')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product',
            field=models.ManyToManyField(through='common.WarehouseProduct', to='common.product'),
        ),
        migrations.CreateModel(
            name='ProductClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='clients',
            field=models.ManyToManyField(through='common.ProductClient', to='common.client'),
        ),
        migrations.CreateModel(
            name='ClientWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveSmallIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.client')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='warehouse',
            field=models.ManyToManyField(through='common.ClientWarehouse', to='common.warehouse'),
        ),
    ]
